### PR TITLE
Update jQuery 3 version to 3.5.0

### PR DESCRIPTION
**Pull request by thenathanjones**
I'm on a project using jquery-rails to manage its jQuery version, and I'm not in a position to upgrade to Webpack as yet. So, I'm submitting this PR to address this security issue: https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

I've updated the jQuery files to fresh versions from the jQuery website, and updated all the relevant places I saw referencing the old version to what I thought was sensible. 

The tests pass locally. Please let me know if you require anything else.

### CODE REVIEW

**Comment by emilong** [comment]
Thanks, @thenathanjones!

For my own curiosity, I thought I'd compare the sources in this commit with the ones I could download from jquery.com and found that the un-minified source matches, but the minified source and map are slightly different:

This commit:
```
aff01a147aeccc9b70a5efad1f2362fd709f3316296ec460d94aa7d31decdb37  jquery3.js
c24f8cb6f6b73be8e5b24580be25ad46aeb91533dd784151bb4f335ec458538e  jquery3.min.js
f3effddc00f5ca49cde3994581b9cf50e017778fa51ff63b3c00f0c08dad4f13  jquery3.min.map
```

What I pulled from jquery.com:
```
aff01a147aeccc9b70a5efad1f2362fd709f3316296ec460d94aa7d31decdb37  jquery-3.5.0.js
c4dccdd9ae25b64078e0c73f273de94f8894d5c99e4741645ece29aeefc9c5a4  jquery-3.5.0.min.js
3149351c8cbc3fb230bbf6188617c7ffda77d9e14333f4f5f0aa1aae379df892  jquery-3.5.0.min.map
```

I'm guessing they did a rebuild since you pulled it?

**Comment by rafaelfranca** [comment]
https://github.com/rails/jquery-rails/blob/master/CONTRIBUTING.md#updating-jquery

**Comment by thenathanjones** [comment]
Hey @rafaelfranca and @emilong thanks for looking at the PR.

No idea regarding the file differences, to be honest it could just be taking whitespace from my editor in hindsight.

If I can't help you update this that's fine, but how can we address this Issue so we can move to the fixed version of jquery? https://github.com/rails/jquery-rails/issues/273

**Comment by thenathanjones** [comment]
@emilong yep, confirmed my editor had broken the formatting. My bad.

**Comment by emilong** [comment]
No worries, @thenathanjones! Thanks for putting up the PR - I too would love to see the upgrade.

**Comment by jrochkind** [comment]
The version of jquery included in the most recent release of jquery-rails has CVE's. Is there anything else anyone  can do to help get jquery updated here?

**Comment by DonikaV** [comment]
Guys the 3.6.0 was released, can someone update, please?

**Pull request closed without merging**
