### PR TITLE
Add Jquery 3.

### PR DESCRIPTION
**Pull request by CUnknown**
It's not very elegant, but it uses the same approach as the Jquery 2 implementation...

### CODE REVIEW

**Comment by CUnknown** [comment]
@rafaelfranca I'm having difficulties figuring out why the tests do not pass on ruby-head on travis. Locally, the tests all pass for ruby-head. Forcing to update bundler before_install also does not seem to work (it could have been an old issue with bundler, and travis does not use the latests version of bundler by default).

**Comment by CUnknown** [comment]
Anyone?

**Comment by udaykadaboina** [comment]
I wonder if your PR will be accepted since the contributing rules say, due to security reasons core team wouldn't accept PRs with any changes/update to jQuery. Instead open an issue.

**Comment by connorshea** [comment]
Yeah, this shouldn't be accepted per the contributing guidelines.

**Pull request closed without merging**
