### PR TITLE
Add patterns for select more jquery functions

### PR DESCRIPTION
**Pull request by plus3x**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Could you add some tests for this?

**Comment by plus3x** [comment]
Ok

**Comment by plus3x** [comment]
Sorry. Can you add test environment on master. I test it on my own project.

**Comment by rafaelfranca** [comment]
Oh, I thought we had included the test environment, so yeah your patch seems good since we don't have tests yet.

I'll work on that tests later.

**Comment by plus3x** [comment]
Thank you)

**Comment by plus3x** [comment]
Test environment #191)

**Pull request merged**
