### PR TITLE
Adds jQuery 3 support

### PR DESCRIPTION
**Pull request by cannikin**
This should contain all the changes necessary to support jQuery 3 _except_ for the actual JS files themselves. I know that for security reasons you can't accept pull requests with new jQuery code. This PR contains the shell of the JS files themselves (to be sure everything is named correctly) but they're empty, ready to be populated with the actual code.

### CODE REVIEW

**Comment by connorshea** [comment]
The build failure is because of mime-types-data dropping support for 1.9.3, apparently.

**Comment by usbsnowcrash** [comment]
It would be cool if there was an option to include jquery3-slim as well.  Any chance this is going to get merged?

**Comment by connorshea** [comment]
@cannikin you should probably either remove Ruby 1.9.3 tests and drop support for it in the gemspec or limit the mime-types version (personally I think the first one is a better choice)

**Comment by cannikin** [comment]
@connorshea I'm waiting on a core member to say which of those two options is preferred...

**Comment by connorshea** [comment]
@cannikin given that the last version of Rails to support 1.9.3 was 4.0, and it recommended at least 2.0, it should be fine to drop support for it.

**Comment by rafaelfranca** [comment]
Could you remove the files inside `vendor/assets/javascripts`?

**Comment by cannikin** [comment]
Done!

**Comment by rafaelfranca** [comment]
Oh, not all of them just the files that were added. Sorry for not being clear.

**Comment by cannikin** [comment]
Whoops! Done again!

**Comment by rafaelfranca** [comment]
Thank you. I'll release it later.

**Pull request merged**
